name: "OwnCloud Infinite Scale"
version: "1.0.0"
slug: "owncloud_ocis"
description: "Запуск OwnCloud Infinite Scale внутри Home Assistant OS"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: application
boot: auto
ports:
  9200/tcp: null  # oCIS будет использовать случайный порт на хосте для избежания конфликтов
map:
  - config:rw
  - share:rw
  - ssl:ro
options:
  ocis_domain: "homeassistant.local"
  admin_password: "admin"
schema:
  ocis_domain: "str"
  admin_password: "str"
